### PR TITLE
Add height to Popup Menu

### PR DESCRIPTION
**Pull request by westhighr**
add a height to the popup Menu for better Usage

### CODE REVIEW

**Comment by coddingtonbear** [comment]
Could you elaborate on what setting this height fixes for you?

**Comment by run-ze** [comment]
> Could you elaborate on what setting this height fixes for you?

it's max height on chrome, a height larger than it will make scrollbar show.
see: https://developer.chrome.com/docs/extensions/reference/browserAction/#popup

but it actually should be 584px because body has 8px margin.

screenshots on windows chrome:

why it need a min height:
image

height: 600px
image

height: 584px
image

**Comment by coddingtonbear** [comment]
At the moment, I'd rather have the dropdown show a scrollbar than have a sea of whitespace below the controls.  Maybe there are alternative UIs you can propose for selecting a template, though, that might avoid the dropdown scrollbar without making the panel be mostly empty?

**Comment by coddingtonbear** [comment]
Closing due to inactivity.  If you'd like to continue this discussion, though, please feel free to propose an alternative UI here.

**Pull request closed without merging**
