### PR TITLE
Add popup shortcut

### PR DESCRIPTION
**Pull request by NZX-DeSiGN**
This commit add a shortcut command to open the extension popup, feel free to ajust the shortcut.

Thank you for this awesome extension !

### CODE REVIEW

**Comment by coddingtonbear** [comment]
Awesome, thanks for the contribution @NZX-DeSiGN; there are a couple things that had held me back from looking into this before, and I wonder if you have any insights into these:

- Is there a way to make this shortcut user-configurable?  I know that in at least my case the particular shortcut you've selected is already assigned to a different extension.  That can always be avoided by picking something difficult-to-type (e.g. `Alt+Shift+O` was what I had to change it to in my local clone of this to test this out), but if it can be made configurable, that would allow folks to pick more-convenient shortcuts if they're available?
- If the above isn't true, I wonder if there's a way to disable the shortcut so a user might be able to let their selected keyboard shortcut be processed by another chrome extension instead of Obsidian Web in the event of a conflict.

**Comment by NZX-DeSiGN** [comment]
Yes in the manifest.json it's just the default shortcut, the user can select a custom shortcut or disable it from the Chrome settings (go to chrome://extensions/shortcuts)

**Comment by coddingtonbear** [comment]
I've spent a little time thinking a bit more about this, and I'm going to hold off on merging this for the moment; sorry for not making my indecision clearer earlier!  Before merging this, what I'd think I'd need is for there to be is the capability of configuring this shortcut from within the in-extension configuration page.

Although as you describe above, it's totally possible for somebody to configure the shortcut from within _chrome_ settings, I imagine that conflicting shortcuts are going to be a regular occurrence, and I'd rather not have to field support requests in the future for that sort of thing.

If you're not personally up for adding that capability, though, @NZX-DeSiGN, that's alright!  I understand if you've already invested the total amount of effort you're willing to invest -- this is an open-source project, and all of us are volunteers with limited time and/or interest -- but I'll keep this PR open for a little while in case you or somebody else would like to take this the next few steps.

**Comment by MisterPresident** [comment]
How about changing the shortcut to a right-click context menu?

**Comment by iwyatt** [comment]
FWIW, I've been able to add a keyboard shortcut to the extension by using Chrome (Brave)'s extension configuration page. I haven't examined this pull request myself, but it might actually be duplicating functionality that already exists within the browser.

**Comment by coddingtonbear** [comment]
Closing due to inactivity.

**Pull request closed without merging**
